### ISSUE TITLE
Catch errors while compiling

### ISSUE THREAD

**Issue by dbr** [karthikv/nodefront#2]
If a `.jade` file contains anything invalid, it throws an error which kills `nodefront compile --live`

```
$ echo "-nonsense" > index.jade
$ nodefront compile -l
Serving your files at http://127.0.0.1:3000/.
   info  - socket.io started

.../test/node_modules/nodefront/node_modules/q/q.js:1305
            throw error;
                  ^
ReferenceError: .../test/index.jade:1
  > 1| -nonsense
    2| 

nonsense is not defined
    at eval at eval at <anonymous> (.../test/node_modules/nodefront/node_modules/jade/lib/jade.js:160:8)
    at .../test/node_modules/nodefront/node_modules/jade/lib/jade.js:165:12
    at Object.render (.../test/node_modules/nodefront/node_modules/jade/lib/jade.js:200:14)
From previous event:
    at Command.<anonymous> (.../test/node_modules/nodefront/commands/compile.js:103:6)
    at Command.<anonymous> (.../test/node_modules/nodefront/node_modules/commander/lib/commander.js:245:8)
    at Command.emit (events.js:88:20)
    at Command.parseArgs (.../test/node_modules/nodefront/node_modules/commander/lib/commander.js:417:12)
    at Command.parse (.../test/node_modules/nodefront/node_modules/commander/lib/commander.js:367:15)
    at Object.<anonymous> (.../test/node_modules/nodefront/nodefront.js:91:9)
$
```

It'd be great if the error was displayed in the browser, so you don't have to look at the terminal to work out why the page stopped reloading

Other than that, it's working perfectly (I've been looking for something to simply reload an HTML file when I reload it - most other options are overly complicated, requiring browser-plugins and such

**Comment by karthikv** [comment]
Ah, you make a good point. I'll address this likely later today, but if something comes up, it may take longer.

**Comment by karthikv** [comment]
Compilation errors are now caught. Version 0.0.5 has been released with the changes.
