### ISSUE TITLE
TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by karthikv** [karthikv/nodefront#23]
cc @ForbesLindesay

Error occurs in `commander-config` due to the `config.withSettings` call on the latest `master` branch. This happens when I run any nodefront command in most any directory; e.g. `nodefront minify script.js`. Traceback included below:

```
/Users/karthikv/Active/nodefront/node_modules/q/q.js:1305
            throw error;
                  ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at mergeSimple (/Users/karthikv/Active/nodefront/node_modules/commander-config/lib/utils.js:57:16)
    at Object.into (/Users/karthikv/Active/nodefront/node_modules/commander-config/lib/utils.js:45:13)
    at /Users/karthikv/Active/nodefront/node_modules/commander-config/index.js:86:28
From previous event:
    at Command.withSettings (/Users/karthikv/Active/nodefront/node_modules/commander-config/index.js:85:38)
    at Command.<anonymous> (/Users/karthikv/Active/nodefront/node_modules/commander/lib/commander.js:234:8)
    at Command.emit (events.js:88:20)
    at Command.parseArgs (/Users/karthikv/Active/nodefront/node_modules/commander/lib/commander.js:406:12)
    at Command.parse (/Users/karthikv/Active/nodefront/node_modules/commander/lib/commander.js:356:15)
    at Object.<anonymous> (/Users/karthikv/Active/nodefront/nodefront.js:98:9)
```

**Comment by ForbesLindesay** [comment]
If you update the commander-config dependency to latest, it should be fixed.

I had assumed that commander always passed env as the first argument,  I have changed the withSettings method so that it searches for an argument that is of type object.  There should only be one of these because any arguments will not be of type object.

**Comment by karthikv** [comment]
Ah, that makes sense. I think there should be a way to specify those positional arguments as well, though, via the config file. Is there any reason why you chose to make commander-config work specifically with commander.js? I think it can be generalized so as to provide a `getSettings` function that simply returns an object with the settings. That way, we can incorporate it into Nodefront for not only the env, but also required arguments to commands (e.g. libraryName for fetch, port/hostname for serve, etc.) by simply extending the settings with the command-line input.

**Comment by ForbesLindesay** [comment]
I've updated the readme for commander-config.  It actually exposes two public methods, so one of them does behave like that, we could use it instead if you prefer?

Alternatively, we could put stuff inside the methods to look for properties on the environment if an argument is not specified?

**Comment by karthikv** [comment]
Let's keep it as is for now and, if we need the added flexibility, we can use the public methods that you exposed.
