### ISSUE TITLE
Error "Error parsing your JSON configuration file" does not say where the file is located

### ISSUE THREAD

**Issue by ghost** [karthikv/nodefront#30]
When unable to parse the config file any subsequent use of the nodefront commandt fails with this error.

In my case I've added a library interactively, but the url did not include the protocol part, e.g. "http", or maybe it's because I forogot to add v before {{ version }}... not sure. Reinstalling nodefront using npm seem to solve the problem.

```
"Error parsing your JSON configuration file
```

Full error:

```
/usr/local/share/npm/lib/node_modules/nodefront/node_modules/nconf/lib/nconf/stores/file.js:132
      throw new Error("Error parsing your JSON configuration file.")
            ^
Error: Error parsing your JSON configuration file.
    at File.loadSync (/usr/local/share/npm/lib/node_modules/nodefront/node_modules/nconf/lib/nconf/stores/file.js:132:13)
    at Provider.add (/usr/local/share/npm/lib/node_modules/nodefront/node_modules/nconf/lib/nconf/provider.js:135:23)
    at Provider.file (/usr/local/share/npm/lib/node_modules/nodefront/node_modules/nconf/lib/nconf/provider.js:61:15)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/nodefront/commands/fetch.js:15:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
```

**Comment by ForbesLindesay** [comment]
Looking at the site of the error, the file being parsed is `/usr/local/share/npm/lib/node_modules/nodefront/libraries.json` which should be installed when you install nodefront.

**Comment by ghost** [comment]
Yes, I saw that, and in my case it was empty.... under ~/.npm/.... though I could see the default content, with nothing to do with me trying to add a new lib.

**Comment by karthikv** [comment]
I'm going to assume for now that this isn't a problem with nodefront, but rather some issue specific to your machine or installation process. Feel free to reopen if this occurs again or seems to affect others.

**Comment by ghost** [comment]
This appears to be from https://github.com/flatiron/nconf
