### ISSUE TITLE
Compilation throwing "Cannot find module 'coffee-script'"

### ISSUE THREAD

**Issue by colintoh** [karthikv/nodefront#4]
Updated to 0.06 and tried compiling for the first time. 

I tried both **$ nodefront compile -l** and **$ nodefront compile -h 0.0.0.0 -r -l**

Got this error message:

_module.js:340
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodefront/commands/compile.js:7:20)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)_

**Comment by karthikv** [comment]
npm has a [known bug](https://github.com/isaacs/npm/issues/2390) with its update command in that it does not install new dependencies for packages. CoffeeScript was added as a dependency in version 0.0.4 and, because of this, has not been installed.

In turn, you'll need to uninstall and then reinstall nodefront, like so:

``` bash
npm uninstall -g nodefront
npm install -g nodefront
```

I'll update this in the README as the standard way to upgrade nodefront from now on, as I don't want this affecting others. Thanks much for the report!

Let me know if this fixes the problem and I'll close this issue.

**Comment by colintoh** [comment]
It worked as advertised. Thanks
